# Generated by Django 4.1.3 on 2022-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='depatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatment', models.CharField(max_length=50, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('job', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('department', models.IntegerField()),
            ],
        ),
    ]
